data:
  train_files: Knowledges,OCRs,Maths,Generals,Charts,Maths
  val_files: demo2
  prompt_key: prompt
  answer_key: answer
  image_key: images
  rollout_batch_size: 16
  max_prompt_length: 8192
  max_response_length: 1024
  use_addition_column: True
  shuffle: true
  seed: 1
  max_pixels: 4194304
  min_pixels: 262144

algorithm:
  adv_estimator: grpo
  kl_coef: 0.0001

worker:
  actor:
    global_batch_size: 16
    micro_batch_size_per_device_for_update: 4
    micro_batch_size_per_device_for_experience: 4
    max_grad_norm: 1
    entropy_coeff: 1.0e-3
    use_kl_loss: true
    kl_loss_coef: 0.1
    kl_loss_type: low_var_kl
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: Qwen/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: true
    optim:
      lr: 5.0e-7
      weight_decay: 1.0e-2
      lr_warmup_ratio: 0.05
    offload:
      offload_params: true
      offload_optimizer: true
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true

  rollout:
    temperature: 1.0
    tensor_parallel_size: 2
    gpu_memory_utilization: 0.4
    n: 8
    enable_chunked_prefill: true
    enforce_eager: false
    limit_images: 0
    max_num_batched_tokens: 12000

  ref:
    offload:
      offload_params: false
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true
      enable_rank0_init: true

  reward:
    reward_type: function 
    compute_score: choice
    val_compute_score: math
    alpha: 800

trainer:
  total_episodes: 5
  logger: ["console", "wandb"]
  project_name: easy_r1
  experiment_name: qwen2_5_7b_bs
  n_gpus_per_node: 8
  nnodes: 1
  val_freq: -1
  val_before_train: false
  val_only: false
  val_generations_to_log: 1
  save_freq: 200
  remove_previous_ckpt: false
  remove_ckpt_after_load: false
  save_checkpoint_path: null
  load_checkpoint_path: null
