data:
  train_files: Math
  val_files: demo2
  prompt_key: prompt
  answer_key: answer
  image_key: images
  rollout_batch_size: 2
  max_prompt_length: 8192
  max_response_length: 1024
  use_addition_column: True
  shuffle: false
  seed: 1
  max_pixels: 1048576 # 4194304
  min_pixels: 262144
  system_prompt: You FIRST think about the reasoning process as an internal monologue and then provide the final answer.The reasoning process MUST BE enclosed within <think> </think> tags. The final answer MUST BE enclosed within <answer> </answer> tags.

algorithm:
  adv_estimator: grpo
  kl_coef: 0.001

worker:
  actor:
    global_batch_size: 2
    micro_batch_size_per_device_for_update: 1
    micro_batch_size_per_device_for_experience: 1
    max_grad_norm: 1.0
    entropy_coeff: 1.0e-3
    use_kl_loss: true
    kl_loss_coef: 1.0e-3
    kl_loss_type: low_var_kl
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: /fs-computility/ai4phys/shared/checkpoints/Qwen2.5-VL-3B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 1.0e-7
      weight_decay: 1.0e-2
      lr_warmup_ratio: 0.0
    offload:
      offload_params: true
      offload_optimizer: true
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true

  rollout:
    temperature: 1.0
    tensor_parallel_size: 1
    gpu_memory_utilization: 0.4
    n: 1
    enable_chunked_prefill: false
    enforce_eager: false
    limit_images: 0

  ref:
    offload:
      offload_params: false
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true
      enable_rank0_init: true

  reward:
    reward_type: function
    compute_score: choice
    val_compute_score: math

trainer:
  total_episodes: 3
  logger: ["console", "wandb"]
  project_name: easy_r1
  experiment_name: qwen2_5_vl_7b_dsw
  n_gpus_per_node: 2
  nnodes: 1
  val_freq: -1
  val_before_train: false
  val_only: false
  val_generations_to_log: 1
  save_freq: 100000
  remove_previous_ckpt: false
  remove_ckpt_after_load: false
  save_checkpoint_path: null
  load_checkpoint_path: null
